/**
 * DOM 元素引用对象。
 * 餀个引用均在模块加载时查询一次，避免在运行时重复访问 DOM。
 * 其他模块均应通过 ui.xxx 访问 DOM 元素而非直接操作 document。
 */
export const ui = {
  canvas: document.getElementById("game-canvas"),
  sunCount: document.getElementById("sun-count"),
  levelLabel: document.getElementById("level-label"),
  waveLabel: document.getElementById("wave-label"),
  renderStat: document.getElementById("render-stat"),
  waveBar: document.getElementById("wave-bar"),
  cardsPanel: document.getElementById("cards-panel"),
  pauseBtn: document.getElementById("pause-btn"),
  speedBtn: document.getElementById("speed-btn"),
  cameraBtn: document.getElementById("camera-btn"),
  shovelBtn: document.getElementById("shovel-btn"),
  settingsBtn: document.getElementById("settings-btn"),
  pauseCover: document.getElementById("pause-cover"),
  toast: document.getElementById("toast"),
  menuOverlay: document.getElementById("menu-overlay"),
  chapterProgress: document.getElementById("chapter-progress"),
  prepOverlay: document.getElementById("prep-overlay"),
  prepTitle: document.getElementById("prep-title"),
  prepDesc: document.getElementById("prep-desc"),
  prepCards: document.getElementById("prep-cards"),
  prepCount: document.getElementById("prep-count"),
  prepStartBtn: document.getElementById("prep-start-btn"),
  prepCancelBtn: document.getElementById("prep-cancel-btn"),
  resultOverlay: document.getElementById("result-overlay"),
  settingsOverlay: document.getElementById("settings-overlay"),
  newGameBtn: document.getElementById("new-game-btn"),
  endlessGameBtn: document.getElementById("endless-game-btn"),
  continueBtn: document.getElementById("continue-btn"),
  menuSettingsBtn: document.getElementById("menu-settings-btn"),
  resultTitle: document.getElementById("result-title"),
  resultDesc: document.getElementById("result-desc"),
  resultStats: document.getElementById("result-stats"),
  retryBtn: document.getElementById("retry-btn"),
  nextBtn: document.getElementById("next-btn"),
  backMenuBtn: document.getElementById("back-menu-btn"),
  volumeInput: document.getElementById("volume-input"),
  defaultSpeedSelect: document.getElementById("default-speed-select"),
  pauseBehaviorSelect: document.getElementById("pause-behavior-select"),
  graphicsQualitySelect: document.getElementById("graphics-quality-select"),
  audioEnabledInput: document.getElementById("audio-enabled-input"),
  performanceModeInput: document.getElementById("performance-mode-input"),
  saveSettingsBtn: document.getElementById("save-settings-btn"),
  cancelSettingsBtn: document.getElementById("cancel-settings-btn"),
};