/**
 * 所有植物的静态配置表，以植物 id 为键。
 * 每个植物对象包含以下字段（部分字段仅特定 kind 有效）：
 *   - id / name：唯一标识与显示名称
 *   - cost：种植所需阳光
 *   - cooldown：卡片冷却时间（秒）
 *   - hp：生命值
 *   - color：Hex 颜色（用于 2D 降级渲染）
 *   - kind：植物类型，决定其行为逻辑
 *     · producer  — 产阳光（sunflower）
 *     · shooter   — 发射豌豆（peashooter / snowpea / repeater / threepeater）
 *     · tank      — 高血量阻挡（wallnut / tallnut）
 *     · trap      — 触发爆炸（potatomine）
 *     · pouncer   — 压制单个僵尸（squash）
 *     · groundtrap — 持续造成地面伤害（spikeweed）
 *     · torch     — 点燃经过的豌豆（torchwood）
 *     · magnet    — 吸取僵尸金属道具（magnetshroom）
 *     · freezebomb — 全屏冻结（iceshroom）
 *     · megabomb  — 超大范围爆炸并留下大坑（doomshroom）
 *     · devourer  — 吞噬单个僵尸（chomper）
 *     · bomb      — 范围爆炸后消失（cherrybomb）
 */
export const PLANTS = {
  sunflower: {
    id: "sunflower",
    name: "向日葵",
    cost: 50,
    cooldown: 7,
    hp: 280,
    color: "#f5c84f",
    kind: "producer",
    sunInterval: 8,
  },
  peashooter: {
    id: "peashooter",
    name: "豌豆射手",
    cost: 100,
    cooldown: 7,
    hp: 300,
    color: "#50a84a",
    kind: "shooter",
    damage: 20,
    fireRate: 1.35,
    projectileSpeed: 280,
  },
  wallnut: {
    id: "wallnut",
    name: "坚果墙",
    cost: 50,
    cooldown: 15,
    hp: 2200,
    color: "#a67646",
    kind: "tank",
  },
  tallnut: {
    id: "tallnut",
    name: "高坚果",
    cost: 125,
    cooldown: 20,
    hp: 3600,
    color: "#94663a",
    kind: "tank",
  },
  potatomine: {
    id: "potatomine",
    name: "土豆雷",
    cost: 25,
    cooldown: 18,
    hp: 300,
    color: "#9d7348",
    kind: "trap",
    armTime: 10,
    radiusCells: 0.95,
    damage: 1800,
  },
  squash: {
    id: "squash",
    name: "窝瓜",
    cost: 50,
    cooldown: 20,
    hp: 300,
    color: "#7e9b34",
    kind: "pouncer",
    triggerRange: 0.95,
    damage: 1800,
  },
  spikeweed: {
    id: "spikeweed",
    name: "地刺",
    cost: 100,
    cooldown: 12,
    hp: 1000,
    color: "#5e8142",
    kind: "groundtrap",
    damage: 16,
    hitInterval: 0.6,
  },
  torchwood: {
    id: "torchwood",
    name: "火炬树桩",
    cost: 175,
    cooldown: 12,
    hp: 1100,
    color: "#8e5a2e",
    kind: "torch",
    boostDamage: 20,
  },
  magnetshroom: {
    id: "magnetshroom",
    name: "磁力菇",
    cost: 100,
    cooldown: 18,
    hp: 300,
    color: "#6a5c86",
    kind: "magnet",
    range: 2.5,
    fireRate: 8,
  },
  iceshroom: {
    id: "iceshroom",
    name: "寒冰菇",
    cost: 75,
    cooldown: 30,
    hp: 300,
    color: "#78b8d6",
    kind: "freezebomb",
    fuse: 0.9,
    damage: 28,
    freezeDuration: 4.5,
  },
  doomshroom: {
    id: "doomshroom",
    name: "毁灭菇",
    cost: 125,
    cooldown: 40,
    hp: 300,
    color: "#5b4a78",
    kind: "megabomb",
    fuse: 1.1,
    radiusCells: 2.25,
    damage: 3600,
    craterDuration: 18,
  },
  chomper: {
    id: "chomper",
    name: "食人花",
    cost: 150,
    cooldown: 18,
    hp: 320,
    color: "#7f4da6",
    kind: "devourer",
    damage: 9999,
    chewTime: 8,
    range: 0.9,
  },
  cherrybomb: {
    id: "cherrybomb",
    name: "樱桃炸弹",
    cost: 150,
    cooldown: 25,
    hp: 999,
    color: "#d65044",
    kind: "bomb",
    fuse: 0.8,
    radiusCells: 1.5,
    damage: 1800,
  },
  snowpea: {
    id: "snowpea",
    name: "寒冰射手",
    cost: 175,
    cooldown: 8,
    hp: 300,
    color: "#7ec8ea",
    kind: "shooter",
    damage: 17,
    fireRate: 1.45,
    projectileSpeed: 280,
    slow: 0.5,
    slowDuration: 3,
  },
  repeater: {
    id: "repeater",
    name: "双发射手",
    cost: 200,
    cooldown: 8,
    hp: 300,
    color: "#2f9a3f",
    kind: "shooter",
    damage: 20,
    fireRate: 1,
    projectileSpeed: 300,
    burst: 2,
    burstGap: 0.12,
  },
  threepeater: {
    id: "threepeater",
    name: "三线射手",
    cost: 325,
    cooldown: 10,
    hp: 300,
    color: "#38984b",
    kind: "shooter",
    damage: 20,
    fireRate: 1.32,
    projectileSpeed: 295,
    spreadRows: [-1, 0, 1],
  },
};