export const PLANTS = {
  sunflower: {
    id: "sunflower",
    name: "向日葵",
    cost: 50,
    cooldown: 7,
    hp: 280,
    color: "#f5c84f",
    kind: "producer",
    sunInterval: 8,
  },
  peashooter: {
    id: "peashooter",
    name: "豌豆射手",
    cost: 100,
    cooldown: 7,
    hp: 300,
    color: "#50a84a",
    kind: "shooter",
    damage: 20,
    fireRate: 1.35,
    projectileSpeed: 280,
  },
  wallnut: {
    id: "wallnut",
    name: "坚果墙",
    cost: 50,
    cooldown: 15,
    hp: 2200,
    color: "#a67646",
    kind: "tank",
  },
  tallnut: {
    id: "tallnut",
    name: "高坚果",
    cost: 125,
    cooldown: 20,
    hp: 3600,
    color: "#94663a",
    kind: "tank",
  },
  potatomine: {
    id: "potatomine",
    name: "土豆雷",
    cost: 25,
    cooldown: 18,
    hp: 300,
    color: "#9d7348",
    kind: "trap",
    armTime: 10,
    radiusCells: 0.95,
    damage: 1800,
  },
  squash: {
    id: "squash",
    name: "窝瓜",
    cost: 50,
    cooldown: 20,
    hp: 300,
    color: "#7e9b34",
    kind: "pouncer",
    triggerRange: 0.95,
    damage: 1800,
  },
  spikeweed: {
    id: "spikeweed",
    name: "地刺",
    cost: 100,
    cooldown: 12,
    hp: 1000,
    color: "#5e8142",
    kind: "groundtrap",
    damage: 16,
    hitInterval: 0.6,
  },
  chomper: {
    id: "chomper",
    name: "食人花",
    cost: 150,
    cooldown: 18,
    hp: 320,
    color: "#7f4da6",
    kind: "devourer",
    damage: 9999,
    chewTime: 8,
    range: 0.9,
  },
  cherrybomb: {
    id: "cherrybomb",
    name: "樱桃炸弹",
    cost: 150,
    cooldown: 25,
    hp: 999,
    color: "#d65044",
    kind: "bomb",
    fuse: 0.8,
    radiusCells: 1.5,
    damage: 1800,
  },
  snowpea: {
    id: "snowpea",
    name: "寒冰射手",
    cost: 175,
    cooldown: 8,
    hp: 300,
    color: "#7ec8ea",
    kind: "shooter",
    damage: 17,
    fireRate: 1.45,
    projectileSpeed: 280,
    slow: 0.5,
    slowDuration: 3,
  },
  repeater: {
    id: "repeater",
    name: "双发射手",
    cost: 200,
    cooldown: 8,
    hp: 300,
    color: "#2f9a3f",
    kind: "shooter",
    damage: 20,
    fireRate: 1,
    projectileSpeed: 300,
    burst: 2,
    burstGap: 0.12,
  },
};